"""Put Manrope inside the documents the browser prints.

    python tools/doc_font.py          # writes frontend/src/docFont.ts

A statement, a tax invoice and a remittance advice are printed from a browser
window rather than built by reportlab, and they were the one set of RX5000
paper still going out in Helvetica. Giving them the same face as everything
else means the face has to travel with them, because these documents are saved,
attached to mail and opened on machines that have never heard of this pharmacy.

WHY IT IS EMBEDDED RATHER THAN LINKED.

A stylesheet link to a font host needs the internet, and these are printed in a
dispensary in Bulawayo whose line is down more often than anybody would like. A
link to the app's own /fonts needs the app, which a saved copy does not have. An
embedded face needs neither, and a document that carries its own type is a
document that looks the same in a year.

WHY IT IS SUBSET.

The full family is 71kB a weight before base64, which is a third again on top.
Three weights of that inside every printed window is a real cost for glyphs no
invoice will ever use. Subsetting to Latin plus the punctuation money and
medicine actually need takes it to about 14kB a weight, and the result is
loaded once per session and cached.

Re-run this when the fonts in backend/app/assets/fonts change. The output is
committed, so nobody needs Python to build the frontend.
"""
from __future__ import annotations

import base64
import pathlib
import tempfile

from fontTools.subset import main as subset

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = ROOT / "backend" / "app" / "assets" / "fonts"
OUT = ROOT / "frontend" / "src" / "docFont.ts"

#: The weights the printed documents actually set: body, the strong figure in
#: a meta strip, the headings, and the name at the top, which is set in the
#: same Extrabold as the title of every sheet reportlab builds. Medium is not
#: used on paper the browser prints, so it is not carried.
WEIGHTS = {"Regular": 400, "Semibold": 600, "Bold": 700, "Extrabold": 800}

#: ASCII, Latin-1 and Latin Extended-A for names, then the marks a pharmacy's
#: paperwork uses: the middot these documents separate facts with, real
#: quotation marks, the currencies a Zimbabwean pharmacy bills in, and the
#: signs that turn up in a dosage or a strength.
CHARS = (
    "".join(chr(c) for c in range(0x20, 0x7F))
    + "".join(chr(c) for c in range(0xA0, 0x180))
    + "·–—‘’“”…°±×÷"
    + "€£™©®−  ½¼¾"
)


def build() -> None:
    unicodes = ",".join(f"U+{ord(c):04X}" for c in sorted(set(CHARS)))
    faces: list[str] = []
    total = 0
    with tempfile.TemporaryDirectory() as tmp:
        for name, weight in WEIGHTS.items():
            src = FONTS / f"Manrope-{name}.ttf"
            if not src.exists():
                raise SystemExit(f"{src} is missing; nothing to embed.")
            dst = pathlib.Path(tmp) / f"{name}.woff2"
            subset([
                str(src), f"--unicodes={unicodes}", "--flavor=woff2",
                "--layout-features=kern,liga,tnum,calt",
                f"--output-file={dst}", "--desubroutinize", "--no-hinting",
            ])
            raw = dst.read_bytes()
            total += len(raw)
            b64 = base64.b64encode(raw).decode("ascii")
            faces.append(
                '  @font-face {\n'
                '    font-family: "Manrope";\n'
                f'    font-weight: {weight};\n'
                '    font-style: normal;\n'
                '    font-display: block;\n'
                f'    src: url(data:font/woff2;base64,{b64}) format("woff2");\n'
                '  }'
            )
            print(f"  {name:<9} {src.stat().st_size:>7,} ttf -> {len(raw):>7,} woff2")

    OUT.write_text(
        "/* Generated by tools/doc_font.py. Do not edit by hand.\n"
        " *\n"
        " * Manrope, subset to Latin and the marks a pharmacy's paperwork uses,\n"
        " * so a printed document carries its own type to wherever it is opened.\n"
        " * Loaded on the first print rather than with the app, which is why it is\n"
        f" * its own module: about {total // 1024}kB of woff2 that a session which\n"
        " * never prints anything never pays for.\n"
        " */\n"
        "export const DOC_FONT = `\n" + "\n".join(faces) + "\n`;\n",
        encoding="utf-8", newline="\n")
    print(f"\n{OUT.relative_to(ROOT)}: {OUT.stat().st_size:,} bytes "
          f"({total:,} of woff2)")


if __name__ == "__main__":
    build()
